level = 2

data : 
	./tsv_to_libfm.py $(level) ../../data/train.tsv ../../data/valid.tsv ../../data/test.tsv ../../data/feature.txt 
	mv ../../data/*.libfm ../../data/tokens.txt ../../data/groups.meta ../libfm_data/v$(level)
